[tool.poetry]
name = "dagster-test"
version = "0.1.0"
description = ""
authors = ["Ronald Miller <ronald.miller@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
dagster = "^1.4.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
